FROM suilteam/cxy:latest-alpine AS builder

# Install packages
RUN apk add --no-cache ruby-rake

# Build the application
COPY . /cxy
WORKDIR /cxy
RUN rake build

FROM alpine:latest
# Build arguments
ARG RELEASE_TAG=v0.1.0

# Set environment variables
ENV RELEASE_TAG=${RELEASE_TAG}

# Set labels
LABEL version="${RELEASE_TAG}"

COPY --from=builder /cxy/.build/cxyfs /usr/local/bin/cxyfs
