FROM suilteam/cxy:latest-ubuntu AS builder

# Install packages
RUN apt-get -y update && apt-get -y upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing ruby

# Build the application
COPY . /cxy
WORKDIR /cxy
RUN rake build

FROM ubuntu:latest
# Build arguments
ARG RELEASE_TAG=v0.1.0

# Set environment variables
ENV RELEASE_TAG=${RELEASE_TAG}

# Set labels
LABEL version="${RELEASE_TAG}"

COPY --from=builder /cxy/.build/cxyfs /usr/local/bin/cxyfs
