FROM suilteam/cxy:latest-alpine AS builder

# Install packages
RUN apk add --no-cache ruby-rake

# Build the application
COPY . /cxy
WORKDIR /cxy
RUN cxy package run release --no-cache

FROM alpine:latest
# Build arguments
ARG RELEASE_TAG=v0.1.0

# Set environment variables
ENV RELEASE_TAG=${RELEASE_TAG}

# Set labels
LABEL version="${RELEASE_TAG}"

COPY --from=builder /cxy/.cxy/artifacts/cxyfs /usr/local/bin/cxyfs
