when:
  - event: tag
    ref: refs/tags/v*

matrix:
  CXY_OS: [alpine, ubuntu]

steps:
  release_cxyfs_docker_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
    commands:
      - docker pull  suilteam/cxy:latest-${CXY_OS}
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - docker build  --build-arg RELEASE_TAG=${CI_COMMIT_TAG} -t suilteam/cxyfs:${CXY_OS}-latest -t suilteam/cxyfs:${CXY_OS}-${CI_COMMIT_TAG} -f Dockerfile.${CXY_OS} .
      - docker push suilteam/cxyfs:${CXY_OS}-latest
      - docker push suilteam/cxyfs:${CXY_OS}-${CI_COMMIT_TAG}
