name: Release cxy playground server image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: suilteam/cxy:latest-ubuntu
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and run tests
        working-directory: ${{github.workspace}}
        run: |
          cxy package build
